# -*- coding: utf-8 -*-
"""Untitled8.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1cm_xqElVNu3RyulOOvtaBNvhmdp3xAES
"""

# -*- coding: utf-8 -*-
"""Untitled6.ipynb
Automatically generated by Colaboratory.
Original file is located at
    https://colab.research.google.com/drive/1o8Qnh8vKV9a0T3DtUIKjIYDfEKOOxbn6
"""

#!/usr/bin/env python
 
import RPi.GPIO as GPIO

GPIO.setmode(GPIO.BCM)

GPIO.setup(10, GPIO.IN)
GPIO.setup(9, GPIO.IN)
GPIO.setup(11, GPIO.IN)
GPIO.setup(7, GPIO.IN)


print GPIO.input(10)

print GPIO.input(9)

print GPIO.input(11)

print GPIO.input(7)